name: SILE

on: [ push, pull_request ]

jobs:

  sile:
    strategy:
      fail-fast: false
      matrix:
        # Test oldest compatible release plus newest patch of each minor bump since
        sileVersion: [ "v0.14.0", "latest" ]
    runs-on: ubuntu-latest
    container:
      image: siletypesetter/sile:${{ matrix.sileVersion }}
      options: --entrypoint=bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run test template
      run: sile -v
